let keywordList = [
    "</FONT> 힘 <FONT color='#FFD200'>", 
    "</FONT> 민첩 <FONT color='#FFD200'>", 
    "</FONT> 지능 <FONT color='#FFD200'>", 
    "</FONT> 공격력 <FONT color='#FFD200'>", 
    "</FONT> 무기 공격력 <FONT color='#FFD200'>", 
    "</FONT> 탈출의 달인 <FONT color='#FFD200'>", 
    "</FONT> 회피의 달인 <FONT color='#FFD200'>", 
    "</FONT> 마나 <FONT color='#FFD200'>", 
    "</FONT> 생명의 축복 <FONT color='#FFD200'>", 
    "</FONT> 자원의 축복 <FONT color='#FFD200'>", 
    "</FONT> 방랑자 <FONT color='#FFD200'>", 
    "</FONT> 무력화 <FONT color='#FFD200'>", 
    "</FONT> 물약 중독 <FONT color='#FFD200'>", 
    "</FONT> 폭발물 달인 <FONT color='#FFD200'>", 
    "</FONT> 행운 (질서) <FONT color='#FFD200'>", 
    "</FONT> 회심 (질서) <FONT color='#FFD200'>", 
    "</FONT> 달인 (질서) <FONT color='#FFD200'>", 
    "</FONT> 강맹 (질서) <FONT color='#FFD200'>", 
    "</FONT> 칼날 방패 (질서) <FONT color='#FFD200'>", 
    "</FONT> 선봉대 (질서) <FONT color='#FFD200'>", 
    "</FONT> 선각자 (질서) <FONT color='#FFD200'>", 
    "</FONT> 진군 (질서) <FONT color='#FFD200'>", 
    "</FONT> 신념 (질서) <FONT color='#FFD200'>", 
    "</FONT> 보스 피해 <FONT color='#FFD200'>", 
    "</FONT> 각성기 피해 <FONT color='#FFD200'>", 
    "</FONT> 보호막 강화 <FONT color='#FFD200'>", 
    "</FONT> 회복 강화 <FONT color='#FFD200'>", 
    "</FONT> 최대 생명력 <FONT color='#FFD200'>", 
    "</FONT> 받는 피해 감소 <FONT color='#FFD200'>", 
    "</FONT> 물리 방어력 <FONT color='#FFD200'>", 
    "</FONT> 마법 방어력 <FONT color='#FFD200'>", 
    "</FONT> 치명타 피해 <FONT color='#FFD200'>", 
    "</FONT> 추가 피해 <FONT color='#FFD200'>", 
    "</FONT> 아이덴티티 획득 <FONT color='#FFD200'>", 
    "</FONT> 아군 강화 <FONT color='#FFD200'>", 
    "</FONT> 행운 (혼돈) <FONT color='#FFD200'>", 
    "</FONT> 회심 (혼돈) <FONT color='#FFD200'>", 
    "</FONT> 달인 (혼돈) <FONT color='#FFD200'>", 
    "</FONT> 강맹 (혼돈) <FONT color='#FFD200'>", 
    "</FONT> 칼날 방패 (혼돈) <FONT color='#FFD200'>", 
    "</FONT> 선봉대 (혼돈) <FONT color='#FFD200'>", 
    "</FONT> 선각자 (혼돈) <FONT color='#FFD200'>", 
    "</FONT> 진군 (혼돈) <FONT color='#FFD200'>", 
    "</FONT> 신념 (혼돈) <FONT color='#FFD200'>"
];


// 악세서리 상중하 구분 필터

let grindingFilter = [
    
    "추가 피해 +0.70%:low",
    "추가 피해 +1.60%:middle",
    "추가 피해 +2.60%:high",
    "적에게 주는 피해 +0.55%:low",
    "적에게 주는 피해 +1.20%:middle",
    "적에게 주는 피해 +2.00%:high",
    "세레나데, 신앙, 조화 게이지 획득량 +1.60%:low",
    "세레나데, 신앙, 조화 게이지 획득량 +3.60%:middle",
    "세레나데, 신앙, 조화 게이지 획득량 +6.00%:high",
    "낙인력 +2.15%:low",
    "낙인력 +4.80%:middle",
    "낙인력 +8.00%:high",
    "최대 생명력 +1300:low",
    "최대 생명력 +3250:middle",
    "최대 생명력 +6500:high",
    "공격력 +80:low",
    "공격력 +195:middle",
    "공격력 +390:high",
    "무기 공격력 +195:low",
    "무기 공격력 +480:middle",
    "무기 공격력 +960:high",
    "최대 마나 +6:low",
    "최대 마나 +15:middle",
    "최대 마나 +30:high",
    "상태이상 공격 지속시간 +0.20%:low",
    "상태이상 공격 지속시간 +0.50%:middle",
    "상태이상 공격 지속시간 +1.00%:high",
    "전투 중 생명력 회복량 +10:low",
    "전투 중 생명력 회복량 +25:middle",
    "전투 중 생명력 회복량 +50:high",
    "공격력 +0.40%:low",
    "공격력 +0.95%:middle",
    "공격력 +1.55%:high",
    "무기 공격력 +0.80%:low",
    "무기 공격력 +1.80%:middle",
    "무기 공격력 +3.00%:high",
    "파티원 회복 효과 +0.95%:low",
    "파티원 회복 효과 +2.10%:middle",
    "파티원 회복 효과 +3.50%:high",
    "파티원 보호막 효과 +0.95%:low",
    "파티원 보호막 효과 +2.10%:middle",
    "파티원 보호막 효과 +3.50%:high",
    "치명타 적중률 +0.40%:low",
    "치명타 적중률 +0.95%:middle",
    "치명타 적중률 +1.55%:high",
    "치명타 피해 +1.10%:low",
    "치명타 피해 +2.40%:middle",
    "치명타 피해 +4.00%:high",
    "아군 공격력 강화 효과 +1.35%:low",
    "아군 공격력 강화 효과 +3.00%:middle",
    "아군 공격력 강화 효과 +5.00%:high",
    "아군 피해량 강화 효과 +2.00%:low",
    "아군 피해량 강화 효과 +4.50%:middle",
    "아군 피해량 강화 효과 +7.50%:high",
]




// 2차전직

let arkFilter = [
    "창술 수련:고기 ",
    "철옹성:전태 ",
    "강인한 육체:비기 ",
    "광기:광기 ",
    "중력 갑옷:분망 ",
    "중력 충격:중수 ",
    "신성한 의무:심판자 ",
    "신성 보호:서폿 ",
    "지치지 않는 힘:처단 ",
    "끝나지 않는 분노:포식 ",
    "기력 회복:체술 ",
    "속도 강화:충단 ",
    "강력한 체술:초심 ",
    "강력한 오의:오의 ",
    "세맥타통:세맥 ",
    "역천지체:역천 ",
    "절제:절제 ",
    "절정:절정 ",
    "오의난무:오의 ",
    "일격필살:일격 ",
    "권왕파천무:권왕 ",
    "수라의 길:수라 ",
    "강화 무기:강무 ",
    "핸드 거너:핸건 ",
    "죽음의 습격:죽습 ",
    "두 번째 동료:두동 ",
    "포격 강화:포강 ",
    "화력 강화:화강 ",
    "진화의 유산:유산 ",
    "아르데타인의 기술:기술 ",
    "피스메이커:피메 ",
    "사냥의 시간:사시 ",
    "황후의 은총:황후 ",
    "황제의 칙령:황제 ",
    "넘치는 교감:교감 ",
    "상급 소환사:상소 ",
    "구원의 선물:서폿 ",
    "진실된 용맹:진실된 용맹 ",
    "점화:점화 ",
    "환류:환류 ",
    "버스트 강화:버스트 ",
    "신속한 일격:잔재 ",
    "멈출 수 없는 충동:충동 ",
    "완벽한 억제:억제 ",
    "달의 소리:달소 ",
    "피냄새:갈증 ",
    "영혼친화력:만월 ",
    "그믐의 경계:그믐 ",
    "해의 조화:서폿 ",
    "회귀:회귀 ",
    "질풍노도:질풍 ",
    "이슬비:이슬비 ",
]


// pow:힘, dex:민첩 , int:지능 중복표기는 힘>민첩>지능 순서로
let bangleJobFilter = [

    {job:"창술 수련",option:"pow",tier:4},
    {job:"철옹성",option:"pow",tier:4},
    {job:"강인한 육체",option:"pow",tier:4},
    {job:"광기",option:"pow",tier:4},
    {job:"중력 갑옷",option:"pow",tier:4},
    {job:"중력 충격",option:"pow",tier:4},
    {job:"신성한 의무",option:"pow",tier:4},
    {job:"신성 보호",option:"pow",tier:4},
    {job:"지치지 않는 힘",option:"pow",tier:4},
    {job:"끝나지 않는 분노",option:"pow",tier:4},
    {job:"기력 회복",option:"pow",tier:4},
    {job:"속도 강화",option:"pow",tier:4},
    {job:"강력한 체술",option:"pow",tier:4},
    {job:"강력한 오의",option:"pow",tier:4},
    {job:"세맥타통",option:"pow",tier:4},
    {job:"역천지체",option:"pow",tier:4},
    {job:"절제",option:"pow",tier:4},
    {job:"절정",option:"pow",tier:4},
    {job:"오의난무",option:"pow",tier:4},
    {job:"일격필살",option:"pow",tier:4},
    {job:"권왕파천무",option:"pow",tier:4},
    {job:"수라의 길",option:"pow",tier:4},
    {job:"강화 무기",option:"dex",tier:4},
    {job:"핸드 거너",option:"dex",tier:4},
    {job:"죽음의 습격",option:"dex",tier:4},
    {job:"두 번째 동료",option:"dex",tier:4},
    {job:"포격 강화",option:"dex",tier:4},
    {job:"화력 강화",option:"dex",tier:4},
    {job:"진화의 유산",option:"dex",tier:4},
    {job:"아르데타인의 기술",option:"dex",tier:4},
    {job:"피스메이커",option:"dex",tier:4},
    {job:"사냥의 시간",option:"dex",tier:4},
    {job:"황후의 은총",option:"int",tier:4},
    {job:"황제의 칙령",option:"int",tier:4},
    {job:"넘치는 교감",option:"int",tier:4},
    {job:"상급 소환사",option:"int",tier:4},
    {job:"구원의 선물",option:"int",tier:4},
    {job:"진실된 용맹",option:"int",tier:4},
    {job:"점화",option:"int",tier:4},
    {job:"환류",option:"int",tier:4},
    {job:"버스트 강화",option:"dex",tier:4},
    {job:"신속한 일격",option:"dex",tier:4},
    {job:"멈출 수 없는 충동",option:"dex",tier:4},
    {job:"완벽한 억제",option:"dex",tier:4},
    {job:"달의 소리",option:"dex",tier:4},
    {job:"피냄새",option:"dex",tier:4},
    {job:"영혼친화력",option:"dex",tier:4},
    {job:"그믐의 경계",option:"dex",tier:4},
    {job:"해의 조화",option:"int",tier:4},
    {job:"회귀",option:"int",tier:4},
    {job:"질풍노도",option:"int",tier:4},
    {job:"이슬비",option:"int",tier:4},



    {job:"광기",option:"pow",tier:3},
    {job:"광전사의 비기",option:"pow",tier:3},
    {job:"고독한 기사",option:"pow",tier:3},
    {job:"처단자",option:"pow",tier:3},
    {job:"포식자",option:"pow",tier:3},
    {job:"전투 태세",option:"pow",tier:3},
    {job:"중력 수련",option:"pow",tier:3},
    {job:"분노의 망치",option:"pow",tier:3},
    {job:"축복의 오라",option:"pow",tier:3,class:"support"},
    {job:"심판자",option:"pow",tier:3},
    {job:"오의 강화",option:"pow",tier:3},
    {job:"초심",option:"pow",tier:3},
    {job:"충격 단련",option:"pow",tier:3},
    {job:"극의: 체술",option:"pow",tier:3},
    {job:"역천지체",option:"pow",tier:3},
    {job:"세맥타통",option:"pow",tier:3},
    {job:"절정",option:"pow",tier:3},
    {job:"절제",option:"pow",tier:3},
    {job:"오의난무",option:"pow",tier:3},
    {job:"일격필살",option:"pow",tier:3},
    {job:"권왕파천무",option:"pow",tier:3},
    {job:"수라의 길",option:"pow",tier:3},
    {job:"강화 무기",option:"dex",tier:3},
    {job:"핸드거너",option:"dex",tier:3},
    {job:"화력 강화",option:"dex",tier:3},
    {job:"포격 강화",option:"dex",tier:3},
    {job:"죽읍의 습격",option:"dex",tier:3},
    {job:"두 번째 동료",option:"dex",tier:3},
    {job:"아르데타인의 기술",option:"dex",tier:3},
    {job:"진화의 유산",option:"dex",tier:3},
    {job:"사냥의 시간",option:"dex",tier:3},
    {job:"피스메이커",option:"dex",tier:3},
    {job:"멈출 수 없는 충동",option:"dex",tier:3},
    {job:"완벽한 억제",option:"dex",tier:3},
    {job:"잔재된 기운",option:"dex",tier:3},
    {job:"버스트",option:"dex",tier:3},
    {job:"갈증",option:"dex",tier:3},
    {job:"달의 소리",option:"dex",tier:3},
    {job:"만월의 집행자",option:"dex",tier:3},
    {job:"그믐의 경계",option:"dex",tier:3},
    {job:"절실한 구원",option:"int",tier:3,class:"support"},
    {job:"진실된 용맹",option:"int",tier:3},
    {job:"상급 소환사",option:"int",tier:3},
    {job:"넘치는 교감",option:"int",tier:3},
    {job:"황후의 은총",option:"int",tier:3},
    {job:"황제의 칙령",option:"int",tier:3},
    {job:"점화",option:"int",tier:3},
    {job:"환류",option:"int",tier:3},
    {job:"회귀",option:"int",tier:3},
    {job:"만개",option:"int",tier:3,class:"support"},
    {job:"질풍노도",option:"int",tier:3},
    {job:"이슬비",option:"int",tier:3}

]



let engravingImg = [

    "각성^https://cdn-lostark.game.onstove.com/EFUI_IconAtlas/Buff/Buff_113.png",
    "강령술^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_29.png",
    "강화 방패^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_239.png",
    "결투의 대가^https://cdn-lostark.game.onstove.com/EFUI_IconAtlas/Ability/Ability_224.png",
    "구슬동자^https://cdn-lostark.game.onstove.com/EFUI_IconAtlas/Buff/Buff_18.png",
    "굳은의지^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_44.png",
    "급소 타격^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_168.png",
    "기습의 대가^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_148.png",
    "긴급구조^https://cdn-lostark.game.onstove.com/EFUI_IconAtlas/Ability/Ability_238.png",
    "달인의 저력^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_147.png",
    "돌격대장^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_210.png",
    "마나 효율 증가^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_166.png",
    "마나의 흐름^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_63.png",
    "바리케이드^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_170.png",
    "번개의분노^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_191.png",
    "부러진 뼈^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_94.png",
    "분쇄의 주먹^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_83.png",
    "불굴^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_66.png",
    "선수필승^https://cdn-lostark.game.onstove.com/efui_iconatlas/achieve/achieve_08_62.png",
    "속전속결^https://cdn-lostark.game.onstove.com/EFUI_IconAtlas/Ability/Ability_236.png",
    "슈퍼 차지^https://cdn-lostark.game.onstove.com/efui_iconatlas/achieve/achieve_06_14.png",
    "승부사^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_136.png",
    "시선 집중^https://cdn-lostark.game.onstove.com/EFUI_IconAtlas/Ability/Ability_234.png",
    "실드 관통^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_89.png",
    "아드레날린^https://cdn-lostark.game.onstove.com/EFUI_IconAtlas/Ability/Ability_235.png",
    "안정된 상태^https://cdn-lostark.game.onstove.com/EFUI_IconAtlas/Buff/Buff_105.png",
    "약자 무시^https://cdn-lostark.game.onstove.com/efui_iconatlas/achieve/achieve_04_30.png",
    "에테르 포식자^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_74.png",
    "여신의 가호^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_229.png",
    "예리한 둔기^https://cdn-lostark.game.onstove.com/efui_iconatlas/achieve/achieve_03_40.png",
    "원한^https://cdn-lostark.game.onstove.com/EFUI_IconAtlas/Buff/Buff_71.png",
    "위기 모면^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_162.png",
    "저주받은 인형^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_237.png",
    "전문의^https://cdn-lostark.game.onstove.com/EFUI_IconAtlas/Ability/Ability_237.png",
    "정기 흡수^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_65.png",
    "정밀 단도^https://cdn-lostark.game.onstove.com/EFUI_IconAtlas/Ability/Ability_239.png",
    "중갑 착용^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_46.png",
    "질량 증가^https://cdn-lostark.game.onstove.com/EFUI_IconAtlas/Ability/Ability_231.png",
    "최대 마나 증가^https://cdn-lostark.game.onstove.com/EFUI_IconAtlas/Buff/Buff_122.png",
    "추진력^https://cdn-lostark.game.onstove.com/EFUI_IconAtlas/Ability/Ability_232.png",
    "타격의 대가^https://cdn-lostark.game.onstove.com/EFUI_IconAtlas/Ability/Ability_233.png",
    "탈출의 명수^https://cdn-lostark.game.onstove.com/efui_iconatlas/buff/buff_10.png",
    "폭발물 전문가^https://cdn-lostark.game.onstove.com/EFUI_IconAtlas/Buff/Buff_121.png",
    "이동속도 감소^https://cdn-lostark.game.onstove.com/EFUI_IconAtlas/Ability/Ability_221.png",
    "공격속도 감소^https://cdn-lostark.game.onstove.com/EFUI_IconAtlas/Ability/Ability_220.png",
    "방어력 감소^https://cdn-lostark.game.onstove.com/EFUI_IconAtlas/Ability/Ability_219.png",
    "공격력 감소^https://cdn-lostark.game.onstove.com/EFUI_IconAtlas/Ability/Ability_218.png",
]





// 전투력 계산식 악세서리 필터 딜러용

let dealerAccessoryFilter = [
    // SP = 딜러특옵 / Support = 서폿기본 / SupportSP = 서폿특옵 / Duel = 딜러서폿 공용 특옵 / Z = 무효 / PUB = 딜러공용옵션 / DuelPub = 딜러서폿 공용 공옵
    "</img>추가 피해 +0.70%:SPlow",
    "</img>추가 피해 +1.60%:SPmiddle",
    "</img>추가 피해 +2.60%:SPhigh",
    "</img>적에게 주는 피해 +0.55%:SPlow",
    "</img>적에게 주는 피해 +1.20%:SPmiddle",
    "</img>적에게 주는 피해 +2.00%:SPhigh",
    "</img>세레나데, 신앙, 조화 게이지 획득량 +1.60%:Supportlow",
    "</img>세레나데, 신앙, 조화 게이지 획득량 +3.60%:Supportmiddle",
    "</img>세레나데, 신앙, 조화 게이지 획득량 +6.00%:Supporthigh",
    "</img>낙인력 +2.15%:SupportSPlow",
    "</img>낙인력 +4.80%:SupportSPmiddle",
    "</img>낙인력 +8.00%:SupportSPhigh",
    "</img>최대 생명력 +1300:Zlow",
    "</img>최대 생명력 +3250:Zmiddle",
    "</img>최대 생명력 +6500:Zhigh",
    "</img>공격력 +80:PUBlow",
    "</img>공격력 +195:PUBmiddle",
    "</img>공격력 +390:PUBhigh",
    "</img>무기 공격력 +195:DuelPublow",
    "</img>무기 공격력 +480:DuelPubmiddle",
    "</img>무기 공격력 +960:DuelPubhigh",
    "</img>최대 마나 +6:Zlow",
    "</img>최대 마나 +15:Zmiddle",
    "</img>최대 마나 +30:Zhigh",
    "</img>상태이상 공격 지속시간 +0.20%:Zlow",
    "</img>상태이상 공격 지속시간 +0.50%:Zmiddle",
    "</img>상태이상 공격 지속시간 +1.00%:Zhigh",
    "</img>전투 중 생명력 회복량 +10:Zlow",
    "</img>전투 중 생명력 회복량 +25:Zmiddle",
    "</img>전투 중 생명력 회복량 +50:Zhigh",
    "</img>공격력 +0.40%:SPlow",
    "</img>공격력 +0.95%:SPmiddle",
    "</img>공격력 +1.55%:SPhigh",
    "</img>무기 공격력 +0.80%:Duellow", 
    "</img>무기 공격력 +1.80%:Duelmiddle",
    "</img>무기 공격력 +3.00%:Duelhigh",
    "</img>파티원 회복 효과 +0.95%:Supportlow",
    "</img>파티원 회복 효과 +2.10%:Supportmiddle",
    "</img>파티원 회복 효과 +3.50%:Supporthigh",
    "</img>파티원 보호막 효과 +0.95%:Supportlow",
    "</img>파티원 보호막 효과 +2.10%:Supportmiddle",
    "</img>파티원 보호막 효과 +3.50%:Supporthigh",
    "</img>치명타 적중률 +0.40%:SPlow",
    "</img>치명타 적중률 +0.95%:SPmiddle",
    "</img>치명타 적중률 +1.55%:SPhigh",
    "</img>치명타 피해 +1.10%:SPlow",
    "</img>치명타 피해 +2.40%:SPmiddle",
    "</img>치명타 피해 +4.00%:SPhigh",
    "</img>아군 공격력 강화 효과 +1.35%:SupportSPlow",
    "</img>아군 공격력 강화 효과 +3.00%:SupportSPmiddle",
    "</img>아군 공격력 강화 효과 +5.00%:SupportSPhigh",
    "</img>아군 피해량 강화 효과 +2.00%:SupportSPlow",
    "</img>아군 피해량 강화 효과 +4.50%:SupportSPmiddle",
    "</img>아군 피해량 강화 효과 +7.50%:SupportSPhigh",
]

// [딜러 : PUB = 유효 공용옵션 / SP1 = 특옵 1순위 / SP2 = 특옵 2순위 / DuelPuB = 서폿과 공용인 유효 공용옵션]
// [서폿 : SupPub = 유효 공용옵션 / DuelPub = 딜러와 공요인 유효 공용옵션 / Sup1 = 특옵 1순위 / Sup2 = 특옵 2순위 / Sup3 = 특옵3순위]
let elixirFilter = [

    "> 공격력 :pub",
    "> 무기 공격력 :DuelPub",
    "> 힘 :DuelPub",
    "> 민첩 :pub",
    "> 지능 :DuelPub",
    "> 행운 :sp", 
    "> 강맹 :sp", 
    "> 칼날방패 :sp", 
    "> 선봉대 :sp", 
    "> 선각자 (질서) :Sup1", 
    "> 선각자 (혼돈) :Sup1", 
    "> 진군 (질서) :Sup2", 
    "> 진군 (혼돈) :Sup2",
    "> 신념 (질서) :Sup2",
    "> 신념 (혼돈) :Sup2",
    "> 회심 (질서) :sp1",
    "> 회심 (혼돈) :sp1",
    "> 달인 (질서) :sp1",
    "> 달인 (혼돈) :sp1",
    "> 보스 피해 :sp2",
    "> 치명타 피해 :sp2",
    "> 추가 피해 :sp2", 
    "> 탈출의 달인 :zero",
    "> 회피의 달인 :zero",
    "> 마나 :SupPub",
    "> 생명의 축복 :zero",
    "> 자원의 축복 :zero",
    "> 방랑자 :zero",
    "> 무력화 :zero",
    "> 물약 중독 :zero",
    "> 폭발물 달인 :zero",
    "> 각성기 피해 :zero",
    "> 보호막 강화 :SupPub",
    "> 회복 강화 :zero",
    "> 최대 생명력 :SupPub",
    "> 받는 피해 감소 :zero",
    "> 물리 방어력 :zero",
    "> 마법 방어력 :zero",
    "> 아이덴티티 획득 :zero",
    "> 아군 강화 :Sup3",
]




let cardPointFilter = [
    '알고 보면:1',
    '너는 계획이 다 있구나:1',
    '에어가이츠 계획:1',
    '남겨진 바람의 절벽:2',
    '창의 달인:2',
    '몰아치는 뇌전의 가호:2',
    '세상을 구하는 빛:2',
    '카제로스의 군단장:2',
    '날랜 뇌전의 숨결:2',
    '굳센 대지의 숨결:2',
    '몰아치는 뇌전의 가호:2',
    '잠재우는 대지의 가호:2'
]




// 접두사 [딜러 : z = 무효 / P = 1티어 옵션 / L = 3티어 옵션 / DuelP = 1티어지만 서폿과 공용 옵션 / Duel = 2티어지만 서폿과 공용 옵션 / DuelL = 3티어지만 서폿과 공용 옵션] 
//        [서폿 : SpP = 1티어 옵션 / SpM =  2티어 옵션 / SpL = 3티어 옵션 / Sp = 4티어 옵션 / Duel = 딜러와 공용 옵션]
let bangleFilter = [
    { name: "공격 및 이동 속도가", option: "3%", tier: "Llow1", initial: "공이속 +3%"},
    { name: "공격 및 이동 속도가", option: "4%", tier: "Llow2", initial: "공이속 +4%"},
    { name: "공격 및 이동 속도가", option: "5%", tier: "Lmiddle", initial: "공이속 +5%"},
    { name: "공격 및 이동 속도가", option: "6%", tier: "Lhigh", initial: "공이속 +6%"},
    { name: "치명타 적중률이", option: "2.6%", tier: "Plow1", initial: "치적 +2.6% | 치명타시 주는 피해 +1.5%"},
    { name: "치명타 적중률이", option: "3.4%", tier: "Plow2", initial: "치적 +3.4% | 치명타시 주는 피해 +1.5%"},
    { name: "치명타 적중률이", option: "4.2%", tier: "Pmiddle", initial: "치적 +4.2% | 치명타시 주는 피해 +1.5%"},
    { name: "치명타 적중률이", option: "5%", tier: "Phigh", initial: "치적 +5.0% | 치명타시 주는 피해 +1.5%"},
    { name: "치명타 피해가", option: "5.2%", tier: "Plow1", initial: "치피 +5.2% | 치명타시 주는 피해 +1.5%"},
    { name: "치명타 피해가", option: "6.8%", tier: "Plow2", initial: "치피 +6.8% | 치명타시 주는 피해 +1.5%"},
    { name: "치명타 피해가", option: "8.4%", tier: "Pmiddle", initial: "치피 +8.4% | 치명타시 주는 피해 +1.5%"},
    { name: "치명타 피해가", option: "10%", tier: "Phigh", initial: "치피 +10.0% | 치명타시 주는 피해 +1.5%"},
    { name: "적에게 주는 피해가", option: "1.5%", tier: "low1", initial: "적에게 주는 피해 +1.5%"},
    { name: "적에게 주는 피해가", option: "2%", tier: "low2", initial: "적에게 주는 피해 +2%"},
    { name: "적에게 주는 피해가", option: "2.5%", tier: "middle", initial: "적에게 주는 피해 +2.5%"},
    { name: "적에게 주는 피해가", option: "3%", tier: "high", initial: "적에게 주는 피해 +3%"},
    { name: "증가하지만, 적에게 주는 피해가", option: "4%", tier: "Plow1", initial: "쿨타임 +2% | 적에게 주는 피해 +4.0%"},
    { name: "증가하지만, 적에게 주는 피해가", option: "4.5%", tier: "Plow2", initial: "쿨타임 +2% | 적에게 주는 피해 +4.5%"},
    { name: "증가하지만, 적에게 주는 피해가", option: "5%", tier: "Pmiddle", initial: "쿨타임 +2% | 적에게 주는 피해 +5.0%"},
    { name: "증가하지만, 적에게 주는 피해가", option: "5.5%", tier: "Phigh", initial: "쿨타임 +2% | 적에게 주는 피해 +5.5%"},
    { name: "추가 피해가", option: "2%", tier: "Plow1", initial: "추피 +2.0% | 악마 및 대악마 피해량 +2.5%"},
    { name: "추가 피해가", option: "2.5%", tier: "Plow2", initial: "추피 +2.5% | 악마 및 대악마 피해량 +2.5%"},
    { name: "추가 피해가", option: "3%", tier: "Pmiddle", initial: "추피 +3.0% | 악마 및 대악마 피해량 +2.5%"},
    { name: "추가 피해가", option: "3.5%", tier: "Phigh", initial: "추피 +3.5% | 악마 및 대악마 피해량 +2.5%"},
    { name: "적에게 공격 적중 시 8초 동안 대상의 방어력을", option: "1.5%", tier: "SpMlow1", initial: "방깎 1.5% | 아군 공격력 강화 +1.5%"},
    { name: "적에게 공격 적중 시 8초 동안 대상의 방어력을", option: "1.8%", tier: "SpMlow2", initial: "방깎 1.8% | 아군 공격력 강화 +2.0%"},
    { name: "적에게 공격 적중 시 8초 동안 대상의 방어력을", option: "2.1%", tier: "SpMmiddle", initial: "방깎 2.1% | 아군 공격력 강화 +2.5%"},
    { name: "적에게 공격 적중 시 8초 동안 대상의 방어력을", option: "2.5%", tier: "SpMhigh", initial: "방깎 2.5% | 아군 공격력 강화 +3.0%"},
    { name: "적에게 공격 적중 시 8초 동안 대상의 치명타 저항을", option: "1.5%", tier: "SpPlow1", initial: "치명타 저항 -1.5% | 아군 공격력 강화 +1.5%"},
    { name: "적에게 공격 적중 시 8초 동안 대상의 치명타 저항을", option: "1.8%", tier: "SpPlow2", initial: "치명타 저항 -1.8% | 아군 공격력 강화 +2.0%"},
    { name: "적에게 공격 적중 시 8초 동안 대상의 치명타 저항을", option: "2.1%", tier: "SpPmiddle", initial: "치명타 저항 -2.1% | 아군 공격력 강화 +2.5%"},
    { name: "적에게 공격 적중 시 8초 동안 대상의 치명타 저항을", option: "2.5%", tier: "SpPhigh", initial: "치명타 저항 -2.5% | 아군 공격력 강화 +3.0%"},
    { name: "파티 효과로 보호 효과(보호막, 생명력 회복, 받는 피해 감소)가 적용된 대상이 5초 동안 적에게 주는 피해가", option: "0.7%", tier: "SpMlow1", initial: "보호 대상의 피해량 +0.7% | 아공강 +1.5%"},
    { name: "파티 효과로 보호 효과(보호막, 생명력 회복, 받는 피해 감소)가 적용된 대상이 5초 동안 적에게 주는 피해가", option: "0.9%", tier: "SpMlow2", initial: "보호 대상의 피해량 +0.9% | 아공강 +2.0%"},
    { name: "파티 효과로 보호 효과(보호막, 생명력 회복, 받는 피해 감소)가 적용된 대상이 5초 동안 적에게 주는 피해가", option: "1.1%", tier: "SpMmiddle", initial: "보호 대상의 피해량 +1.1% | 아공강 +2.5%"},
    { name: "파티 효과로 보호 효과(보호막, 생명력 회복, 받는 피해 감소)가 적용된 대상이 5초 동안 적에게 주는 피해가", option: "1.3%", tier: "SpMhigh", initial: "보호 대상의 피해량 +1.3% | 아공강 +3.0%"},
    { name: "적에게 공격 적중 시 8초 동안 대상의 치명타 피해 저항을", option: "3%", tier: "SpMlow1", initial: "치명타 피해 저항 -3.0% | 아공강 +1.5%"},
    { name: "적에게 공격 적중 시 8초 동안 대상의 치명타 피해 저항을", option: "3.6%", tier: "SpMlow2", initial: "치명타 피해 저항 -3.6% | 아공강 +2.0%"},
    { name: "적에게 공격 적중 시 8초 동안 대상의 치명타 피해 저항을", option: "4.2%", tier: "SpMmiddle", initial: "치명타 피해 저항 -4.2% | 아공강 +2.5%"},
    { name: "적에게 공격 적중 시 8초 동안 대상의 치명타 피해 저항을", option: "4.8%", tier: "SpMhigh", initial: "치명타 피해 저항 -4.8% | 아공강 +3.0%"},
    { name: "공격 적중 시 매 초마다 10초 동안 무기 공격력이", option: "1000", tier: "DuelLlow1", initial: "공격 적중 시 무공 1000, 공이속 1% 증가"},
    { name: "공격 적중 시 매 초마다 10초 동안 무기 공격력이", option: "1160", tier: "DuelLlow2", initial: "공격 적중 시 무공 1160, 공이속 1% 증가"},
    { name: "공격 적중 시 매 초마다 10초 동안 무기 공격력이", option: "1320", tier: "DuelLmiddle", initial: "공격 적중 시 무공 1320, 공이속 1% 증가"},
    { name: "공격 적중 시 매 초마다 10초 동안 무기 공격력이", option: "1480", tier: "DuelLhigh", initial: "공격 적중 시 무공 1480, 공이속 1% 증가"},
    { name: "무기 공격력이", option: "6300", tier: "DuelPlow1", initial: "무공 6300 증가 | 조건부 무공 1800 증가"},
    { name: "무기 공격력이", option: "7200", tier: "DuelPlow2", initial: "무공 7200 증가 | 조건부 무공 2000 증가"},
    { name: "무기 공격력이", option: "8100", tier: "DuelPmiddle", initial: "무공 8100 증가 | 조건부 무공 2200 증가"},
    { name: "무기 공격력이", option: "9000", tier: "DuelPhigh", initial: "무공 9000 증가 | 조건부 무공 2400 증가"},
    { name: "무기 공격력이", option: "6000", tier: "Duellow1", initial: "무공 6000 증가 | 스택당 무공 120 증가"},
    { name: "무기 공격력이", option: "6900", tier: "Duellow2", initial: "무공 6900 증가 | 스택당 무공 130 증가"},
    { name: "무기 공격력이", option: "7800", tier: "Duelmiddle", initial: "무공 7800 증가 | 스택당 무공 140 증가"},
    { name: "무기 공격력이", option: "8700", tier: "Duelhigh", initial: "무공 8700 증가 | 스택당 무공 150 증가"},
    { name: "백어택 스킬이 적에게 주는 피해가", option: "2%", tier: "low1", initial: "백어택 스킬 피해 +2.0%"},
    { name: "백어택 스킬이 적에게 주는 피해가", option: "2.5%", tier: "low2", initial: "백어택 스킬 피해 +2.5%"},
    { name: "백어택 스킬이 적에게 주는 피해가", option: "3%", tier: "middle", initial: "백어택 스킬 피해 +3.0%"},
    { name: "백어택 스킬이 적에게 주는 피해가", option: "3.5%", tier: "high", initial: "백어택 스킬 피해 +3.5%"},
    { name: "헤드어택 스킬이 적에게 주는 피해가", option: "2%", tier: "low1", initial: "헤드어택 스킬 피해 +2.0%"},
    { name: "헤드어택 스킬이 적에게 주는 피해가", option: "2.5%", tier: "low2", initial: "헤드어택 스킬 피해 +2.5%"},
    { name: "헤드어택 스킬이 적에게 주는 피해가", option: "3%", tier: "middle", initial: "헤드어택 스킬 피해 +3.0%"},
    { name: "헤드어택 스킬이 적에게 주는 피해가", option: "3.5%", tier: "high", initial: "헤드어택 스킬 피해 +3.5%"},
    { name: "방향성 공격이 아닌 스킬이 적에게 주는 피해가", option: "2%", tier: "low1", initial: "타대 스킬 피해 +2.0%"},
    { name: "방향성 공격이 아닌 스킬이 적에게 주는 피해가", option: "2.5%", tier: "low2", initial: "타대 스킬 피해 +2.5%"},
    { name: "방향성 공격이 아닌 스킬이 적에게 주는 피해가", option: "3%", tier: "middle", initial: "타대 스킬 피해 +3.0%"},
    { name: "방향성 공격이 아닌 스킬이 적에게 주는 피해가", option: "3.5%", tier: "high", initial: "타대 스킬 피해 +3.5%"},
    { name: "파티원 보호 및 회복 효과가", option: "2%", tier: "Splow1", initial: "보호 및 회복 효과 +2.0%"},
    { name: "파티원 보호 및 회복 효과가", option: "2.5%", tier: "Splow2", initial: "보호 및 회복 효과 +2.5%"},
    { name: "파티원 보호 및 회복 효과가", option: "3%", tier: "Spmiddle", initial: "보호 및 회복 효과 +3.0%"},
    { name: "파티원 보호 및 회복 효과가", option: "3.5%", tier: "Sphigh", initial: "보호 및 회복 효과 +3.5%"},
    { name: "추가 피해 +2.50%", option: null, tier: "Llow1", initial: "추가 피해 +2.5%"},
    { name: "추가 피해 +3.00%", option: null, tier: "Llow2", initial: "추가 피해 +3.0%"},
    { name: "추가 피해 +3.50%", option: null, tier: "Lmiddle", initial: "추가 피해 +3.5%"},
    { name: "추가 피해 +4.00%", option: null, tier: "Lhigh", initial: "추가 피해 +4.0%"},
    { name: "아군 공격력 강화 효과 +3.00%", option: null, tier: "SpLlow1", initial: "아군 공격력 강화 효과 +3.0%"},
    { name: "아군 공격력 강화 효과 +4.00%", option: null, tier: "SpLlow2", initial: "아군 공격력 강화 효과 +4.0%"},
    { name: "아군 공격력 강화 효과 +5.00%", option: null, tier: "SpLmiddle", initial: "아군 공격력 강화 효과 +5.0%"},
    { name: "아군 공격력 강화 효과 +6.00%", option: null, tier: "SpLhigh", initial: "아군 공격력 강화 효과 +6.0%"},
    { name: "아군 피해량 강화 효과 +4.50%", option: null, tier: "SpLlow1", initial: "아군 피해량 강화 효과 +4.5%"},
    { name: "아군 피해량 강화 효과 +6.00%", option: null, tier: "SpLlow2", initial: "아군 피해량 강화 효과 +6.0%"},
    { name: "아군 피해량 강화 효과 +7.50%", option: null, tier: "SpLmiddle", initial: "아군 피해량 강화 효과 +7.5%"},
    { name: "아군 피해량 강화 효과 +9.00%", option: null, tier: "SpLhigh", initial: "아군 피해량 강화 효과 +9.0%"},
    { name: "치명타 적중률 +2.60%", option: null, tier: "low1", initial: "치명타 적중률 +2.60%"},
    { name: "치명타 적중률 +3.40%", option: null, tier: "low2", initial: "치명타 적중률 +3.40%"},
    { name: "치명타 적중률 +4.20%", option: null, tier: "middle", initial: "치명타 적중률 +4.20%"},
    { name: "치명타 적중률 +5.00%", option: null, tier: "high", initial: "치명타 적중률 +5.00%"},
    { name: "치명타 피해 +5.20%", option: null, tier: "low1", initial: "치명타 피해 +5.2%"},
    { name: "치명타 피해 +6.80%", option: null, tier: "low2", initial: "치명타 피해 +6.8%"},
    { name: "치명타 피해 +8.40%", option: null, tier: "middle", initial: "치명타 피해 +8.4%"},
    { name: "치명타 피해 +10.00%", option: null, tier: "high", initial: "치명타 피해 +10.0%"},
    { name: "시드 등급 이하 몬스터에게 주는 피해량이", option: "3%", tier: "zlow1", initial: "시드 이하 몬스터에게 주는 피해량 +3%"},
    { name: "시드 등급 이하 몬스터에게 주는 피해량이", option: "4%", tier: "zlow2", initial: "시드 이하 몬스터에게 주는 피해량 +4%"},
    { name: "시드 등급 이하 몬스터에게 주는 피해량이", option: "5%", tier: "zmiddle", initial: "시드 이하 몬스터에게 주는 피해량 +5%"},
    { name: "시드 등급 이하 몬스터에게 주는 피해량이", option: "6%", tier: "zhigh", initial: "시드 이하 몬스터에게 주는 피해량 +6%"},
    { name: "시드 등급 이하 몬스터에게 받는 피해량이", option: "4%", tier: "zlow1", initial: "시드 이하 몬스터에게 받는 피해량 +4%"},
    { name: "시드 등급 이하 몬스터에게 받는 피해량이", option: "6%", tier: "zlow2", initial: "시드 이하 몬스터에게 받는 피해량 +6%"},
    { name: "시드 등급 이하 몬스터에게 받는 피해량이", option: "8%", tier: "zmiddle", initial: "시드 이하 몬스터에게 받는 피해량 +8%"},
    { name: "시드 등급 이하 몬스터에게 받는 피해량이", option: "10%", tier: "zhigh", initial: "시드 이하 몬스터에게 받는 피해량 +10%"},
    { name: "물리 방어력 +4000", option: null, tier: "zlow1", initial: "물리 방어력 +4000"},
    { name: "물리 방어력 +5000", option: null, tier: "zlow2", initial: "물리 방어력 +5000"},
    { name: "물리 방어력 +6000", option: null, tier: "zmiddle", initial: "물리 방어력 +6000"},
    { name: "물리 방어력 +7000", option: null, tier: "zhigh", initial: "물리 방어력 +7000"},
    { name: "마법 방어력 +4000", option: null, tier: "zlow1", initial: "마법 방어력 +4000"},
    { name: "마법 방어력 +5000", option: null, tier: "zlow2", initial: "마법 방어력 +5000"},
    { name: "마법 방어력 +6000", option: null, tier: "zmiddle", initial: "마법 방어력 +6000"},
    { name: "마법 방어력 +7000", option: null, tier: "zhigh", initial: "마법 방어력 +7000"},
    { name: "최대 생명력 +8400", option: null, tier: "zlow1", initial : "최대 생명력 +8400"},
    { name: "최대 생명력 +11200", option: null, tier: "zlow2", initial : "최대 생명력 +11200"},
    { name: "최대 생명력 +14000", option: null, tier: "zmiddle", initial : "최대 생명력 +14000"},
    { name: "최대 생명력 +16800", option: null, tier: "zhigh", initial : "최대 생명력 +16800"},
    { name: "전투 중 생명력 회복량 +80", option: null, tier: "zlow1", initial : "전투 중 생명력 회복량 +80"},
    { name: "전투 중 생명력 회복량 +100", option: null, tier: "zlow2", initial : "전투 중 생명력 회복량 +100"},
    { name: "전투 중 생명력 회복량 +130", option: null, tier: "zmiddle", initial : "전투 중 생명력 회복량 +130"},
    { name: "전투 중 생명력 회복량 +160", option: null, tier: "zhigh", initial : "전투 중 생명력 회복량 +160"},
    { name: "전투자원 자연 회복량 +6.00%", option: null, tier: "zlow1", initial : "전투자원 자연 회복량 +6%"},
    { name: "전투자원 자연 회복량 +8.00%", option: null, tier: "zlow2", initial : "전투자원 자연 회복량 +8%"},
    { name: "전투자원 자연 회복량 +10.00%", option: null, tier: "zmiddle", initial : "전투자원 자연 회복량 +10%"},
    { name: "전투자원 자연 회복량 +12.00%", option: null, tier: "zhigh", initial : "전투자원 자연 회복량 +12%"},
    { name: "이동기 및 기상기 재사용 대기 시간이", option: "6%", tier: "zlow1", initial: "이동기 및 기상기 쿨감 +6%"},
    { name: "이동기 및 기상기 재사용 대기 시간이", option: "8%", tier: "zlow2", initial: "이동기 및 기상기 쿨감 +8%"},
    { name: "이동기 및 기상기 재사용 대기 시간이", option: "10%", tier: "zmiddle", initial: "이동기 및 기상기 쿨감 +10%"},
    { name: "이동기 및 기상기 재사용 대기 시간이", option: "12%", tier: "zhigh", initial: "이동기 및 기상기 쿨감 +12%"},
    { name: "공격 적중 시", option: "90", tier: "zlow1", initial: "공격 적중 시 90초간 경피면"},
    { name: "공격 적중 시", option: "80", tier: "zlow2", initial: "공격 적중 시 80초간 경피면"},
    { name: "공격 적중 시", option: "70", tier: "zmiddle", initial: "공격 적중 시 70초간 경피면"},
    { name: "공격 적중 시", option: "60", tier: "zhigh", initial: "공격 적중 시 60초간 경피면"},
    { name: "무기 공격력 +6300", option: null, tier: "Duellow1", initial: "무기 공격력 +6300"},
    { name: "무기 공격력 +7200", option: null, tier: "Duellow2", initial: "무기 공격력 +7200"},
    { name: "무기 공격력 +8100", option: null, tier: "Duelmiddle", initial: "무기 공격력 +8100"},
    { name: "무기 공격력 +9000", option: null, tier: "Duelhigh", initial: "무기 공격력 +9000"},
    //아래로 3T 옵션
    { name: "최대 생명력 +5500", option: null, tier: "zlow1", initial : "최대 생명력 +5500"},
    { name: "최대 생명력 +7300", option: null, tier: "zlow2", initial : "최대 생명력 +7300"},
    { name: "최대 생명력 +9100", option: null, tier: "zmiddle", initial : "최대 생명력 +9100"},
    { name: "최대 생명력 +11000", option: null, tier: "zhigh", initial : "최대 생명력 +11000"},
    { name: "최대 마나 +150", option: null, tier: "zlow1", initial : "최대 마나 +150"},
    { name: "최대 마나 +200", option: null, tier: "zlow2", initial : "최대 마나 +200"},
    { name: "최대 마나 +250", option: null, tier: "zmiddle", initial : "최대 마나 +250"},
    { name: "최대 마나 +300", option: null, tier: "zhigh", initial : "최대 마나 +300"},
    { name: "물리 방어력 +500", option: null, tier: "zlow1", initial : "물리 방어력 +500"},
    { name: "물리 방어력 +1200", option: null, tier: "zlow2", initial : "물리 방어력 +1200"},
    { name: "물리 방어력 +2500", option: null, tier: "zmiddle", initial : "물리 방어력 +2500"},
    { name: "물리 방어력 +4000", option: null, tier: "zhigh", initial : "물리 방어력 +4000"},
    { name: "] 기상기 사용 후 4초 동안 인내가", option: "100", tier: "zlow1", initial: "오뚝이"},
    { name: "] 기상기 사용 후 4초 동안 인내가", option: "130", tier: "zlow2", initial: "오뚝이"},
    { name: "] 기상기 사용 후 4초 동안 인내가", option: "160", tier: "zmiddle", initial: "오뚝이"},
    { name: "] 기상기 사용 후 4초 동안 인내가", option: "200", tier: "zhigh", initial: "오뚝이"},
    { name: "] 이동기 사용 후 4초 동안 신속이", option: "50", tier: "zlow1", initial: "돌진"},
    { name: "] 이동기 사용 후 4초 동안 신속이", option: "65", tier: "zlow2", initial: "돌진"},
    { name: "] 이동기 사용 후 4초 동안 신속이", option: "80", tier: "zmiddle", initial: "돌진"},
    { name: "] 이동기 사용 후 4초 동안 신속이", option: "100", tier: "zhigh", initial: "돌진"},
    { name: "] 이동기 사용 후 4초 동안 제압이", option: "50", tier: "zlow1", initial: "강타"},
    { name: "] 이동기 사용 후 4초 동안 제압이", option: "65", tier: "zlow2", initial: "강타"},
    { name: "] 이동기 사용 후 4초 동안 제압이", option: "80", tier: "zmiddle", initial: "강타"},
    { name: "] 이동기 사용 후 4초 동안 제압이", option: "100", tier: "zhigh", initial: "강타"},
    { name: "] 기본 공격 적중 후 4초 동안 숙련이", option: "100", tier: "zlow1", initial: "타격"},
    { name: "] 기본 공격 적중 후 4초 동안 숙련이", option: "130", tier: "zlow2", initial: "타격"},
    { name: "] 기본 공격 적중 후 4초 동안 숙련이", option: "160", tier: "zmiddle", initial: "타격"},
    { name: "] 기본 공격 적중 후 4초 동안 숙련이", option: "200", tier: "zhigh", initial: "타격"},
    { name: "] 마나를 소모하는 스킬 사용 시 20% 확률로 마나를", option: "125", tier: "Splow1", initial: "마나회수"},
    { name: "] 마나를 소모하는 스킬 사용 시 20% 확률로 마나를", option: "150", tier: "Splow2", initial: "마나회수"},
    { name: "] 마나를 소모하는 스킬 사용 시 20% 확률로 마나를", option: "175", tier: "Spmiddle", initial: "마나회수"},
    { name: "] 마나를 소모하는 스킬 사용 시 20% 확률로 마나를", option: "200", tier: "Sphigh", initial: "마나회수"},
    { name: "] 몬스터에게 피격 시", option: "7%", tier: "zlow1", initial: "속공"},
    { name: "] 몬스터에게 피격 시", option: "10%", tier: "zlow2", initial: "속공"},
    { name: "] 몬스터에게 피격 시", option: "12%", tier: "zmiddle", initial: "속공"},
    { name: "] 몬스터에게 피격 시", option: "15%", tier: "zhigh", initial: "속공"},
    { name: "] 배틀 아이템 사용 후 8초 동안 무기 공격력이", option: "1300", tier: "zlow1", initial: "투자"},
    { name: "] 배틀 아이템 사용 후 8초 동안 무기 공격력이", option: "1600", tier: "zlow2", initial: "투자"},
    { name: "] 배틀 아이템 사용 후 8초 동안 무기 공격력이", option: "2200", tier: "zmiddle", initial: "투자"},
    { name: "] 배틀 아이템 사용 후 8초 동안 무기 공격력이", option: "3000", tier: "zhigh", initial: "투자"},
    { name: "] 생명력이", option: "10%", tier: "zlow1", initial: "반전"},
    { name: "] 생명력이", option: "15%", tier: "zlow2", initial: "반전"},
    { name: "] 생명력이", option: "20%", tier: "zmiddle", initial: "반전"},
    { name: "] 생명력이", option: "25%", tier: "zhigh", initial: "반전"},
    { name: "] 60레벨 이하 시드 등급 이하 몬스터에게 주는 피해량이", option: "2%", tier: "zlow1", initial: "멸시"},
    { name: "] 60레벨 이하 시드 등급 이하 몬스터에게 주는 피해량이", option: "3%", tier: "zlow2", initial: "멸시"},
    { name: "] 60레벨 이하 시드 등급 이하 몬스터에게 주는 피해량이", option: "4%", tier: "zmiddle", initial: "멸시"},
    { name: "] 60레벨 이하 시드 등급 이하 몬스터에게 주는 피해량이", option: "5%", tier: "zhigh", initial: "멸시"},
    { name: "] 60레벨 이하 시드 등급 이하 몬스터에게 받는 피해량이", option: "3%", tier: "zlow1", initial: "무시"},
    { name: "] 60레벨 이하 시드 등급 이하 몬스터에게 받는 피해량이", option: "5%", tier: "zlow2", initial: "무시"},
    { name: "] 60레벨 이하 시드 등급 이하 몬스터에게 받는 피해량이", option: "7%", tier: "zmiddle", initial: "무시"},
    { name: "] 60레벨 이하 시드 등급 이하 몬스터에게 받는 피해량이", option: "10%", tier: "zhigh", initial: "무시"},
    { name: "전투 중 생명력 회복량 +40", option: null, tier: "zlow1"},
    { name: "전투 중 생명력 회복량 +50", option: null, tier: "zlow2"},
    { name: "전투 중 생명력 회복량 +65", option: null, tier: "zmiddle"},
    { name: "전투 중 생명력 회복량 +80", option: null, tier: "high"},
    { name: "] 기상기 사용 후 20초 동안 매 초마다 생명력을", option: "80", tier: "zlow1", initial: "회생"},
    { name: "] 기상기 사용 후 20초 동안 매 초마다 생명력을", option: "100", tier: "zlow2", initial: "회생"},
    { name: "] 기상기 사용 후 20초 동안 매 초마다 생명력을", option: "130", tier: "zmiddle", initial: "회생"},
    { name: "] 기상기 사용 후 20초 동안 매 초마다 생명력을", option: "160", tier: "zhigh", initial: "회생"},
    { name: "] 생명력이 50% 이하일 경우 몬스터에게 피격 시 30% 확률로 생명력을", option: "90", tier: "zlow1", initial: "긴급수혈"},
    { name: "] 생명력이 50% 이하일 경우 몬스터에게 피격 시 30% 확률로 생명력을", option: "80", tier: "zlow2", initial: "긴급수혈"},
    { name: "] 생명력이 50% 이하일 경우 몬스터에게 피격 시 30% 확률로 생명력을", option: "70", tier: "zmiddle", initial: "긴급수혈"},
    { name: "] 생명력이 50% 이하일 경우 몬스터에게 피격 시 30% 확률로 생명력을", option: "60", tier: "zhigh", initial: "긴급수혈"},
    { name: "] 생명력이 30% 이하에서 피격 시 5초 동안 회복 배틀 아이템의 회복량을", option: "4000", tier: "zlow1", initial: "응급처치"},
    { name: "] 생명력이 30% 이하에서 피격 시 5초 동안 회복 배틀 아이템의 회복량을", option: "5000", tier: "zlow2", initial: "응급처치"},
    { name: "] 생명력이 30% 이하에서 피격 시 5초 동안 회복 배틀 아이템의 회복량을", option: "6500", tier: "zmiddle", initial: "응급처치"},
    { name: "] 생명력이 30% 이하에서 피격 시 5초 동안 회복 배틀 아이템의 회복량을", option: "8000", tier: "zhigh", initial: "응급처치"},
    { name: "] 배틀 아이템 중 회복계열 사용 시", option: "12%", tier: "zlow1", initial: "앵콜"},
    { name: "] 배틀 아이템 중 회복계열 사용 시", option: "16%", tier: "zlow2", initial: "앵콜"},
    { name: "] 배틀 아이템 중 회복계열 사용 시", option: "20%", tier: "zmiddle", initial: "앵콜"},
    { name: "] 배틀 아이템 중 회복계열 사용 시", option: "25%", tier: "zhigh", initial: "앵콜"},
    { name: "쐐기 : 공격 적중 시 추가 피해가", option: "0.3%", tier: "low1", initial: "쐐기"},
    { name: "쐐기 : 공격 적중 시 추가 피해가", option: "0.35%", tier: "low2", initial: "쐐기"},
    { name: "쐐기 : 공격 적중 시 추가 피해가", option: "0.45%", tier: "middle", initial: "쐐기"},
    { name: "쐐기 : 공격 적중 시 추가 피해가", option: "0.5%", tier: "high", initial: "쐐기"},
    { name: "망치 : 공격 적중 시 치명타 피해량이", option: "6%", tier: "low1", initial: "망치"},
    { name: "망치 : 공격 적중 시 치명타 피해량이", option: "8%", tier: "low2", initial: "망치"},
    { name: "망치 : 공격 적중 시 치명타 피해량이", option: "10%", tier: "middle", initial: "망치"},
    { name: "망치 : 공격 적중 시 치명타 피해량이", option: "12%", tier: "high", initial: "망치"},
    { name: "순환 : 10초 간격으로 스킬 피해", option: "2.5%", tier: "low1", initial: "순환"},
    { name: "순환 : 10초 간격으로 스킬 피해", option: "3%", tier: "low2", initial: "순환"},
    { name: "순환 : 10초 간격으로 스킬 피해", option: "3.5%", tier: "middle", initial: "순환"},
    { name: "순환 : 10초 간격으로 스킬 피해", option: "4%", tier: "high", initial: "순환"},
    { name: "열정 : 몬스터에게 주는 피해가", option: "2.5%", tier: "low1", initial: "열정"},
    { name: "열정 : 몬스터에게 주는 피해가", option: "3%", tier: "low2", initial: "열정"},
    { name: "열정 : 몬스터에게 주는 피해가", option: "3.5%", tier: "middle", initial: "열정"},
    { name: "열정 : 몬스터에게 주는 피해가", option: "4%", tier: "high", initial: "열정"},
    { name: "냉정 : 몬스터에게 주는 피해가", option: "2.5%", tier: "low1", initial: "냉정"},
    { name: "냉정 : 몬스터에게 주는 피해가", option: "3%", tier: "low2", initial: "냉정"},
    { name: "냉정 : 몬스터에게 주는 피해가", option: "3.5%", tier: "middle", initial: "냉정"},
    { name: "냉정 : 몬스터에게 주는 피해가", option: "4%", tier: "high", initial: "냉정"},
    { name: "] 몬스터에게 공격 적중 시 8초 동안 대상의 방어력을", option: "1.5%", tier: "SpMlow1", initial: "비수"},
    { name: "] 몬스터에게 공격 적중 시 8초 동안 대상의 방어력을", option: "1.8%", tier: "SpMlow2", initial: "비수"},
    { name: "] 몬스터에게 공격 적중 시 8초 동안 대상의 방어력을", option: "2.1%", tier: "SpMmiddle", initial: "비수"},
    { name: "] 몬스터에게 공격 적중 시 8초 동안 대상의 방어력을", option: "2.5%", tier: "SpMhigh", initial: "비수"},
    { name: "] 몬스터에게 공격 적중 시 8초 동안 대상의 치명타 저항을", option: "1.5%", tier: "SpPlow1", initial: "약점 노출"},
    { name: "] 몬스터에게 공격 적중 시 8초 동안 대상의 치명타 저항을", option: "1.8%", tier: "SpPlow2", initial: "약점 노출"},
    { name: "] 몬스터에게 공격 적중 시 8초 동안 대상의 치명타 저항을", option: "2.1%", tier: "SpPmiddle", initial: "약점 노출"},
    { name: "] 몬스터에게 공격 적중 시 8초 동안 대상의 치명타 저항을", option: "2.5%", tier: "SpPhigh", initial: "약점 노출"},
    { name: "] 몬스터에게 공격 적중 시 8초 동안 스킬 적중 시 아이덴티티 게이지 획득량이", option: "3%", tier: "zlow1", initial: "깨달음"},
    { name: "] 몬스터에게 공격 적중 시 8초 동안 스킬 적중 시 아이덴티티 게이지 획득량이", option: "4%", tier: "zlow2", initial: "깨달음"},
    { name: "] 몬스터에게 공격 적중 시 8초 동안 스킬 적중 시 아이덴티티 게이지 획득량이", option: "5%", tier: "zmiddle", initial: "깨달음"},
    { name: "] 몬스터에게 공격 적중 시 8초 동안 스킬 적중 시 아이덴티티 게이지 획득량이", option: "6%", tier: "zhigh", initial: "깨달음"},
    { name: "응원 : 몬스터에게 공격 적중 시 주는 피해가", option: "0.7%", tier: "SpMlow1", initial: "응원"},
    { name: "응원 : 몬스터에게 공격 적중 시 주는 피해가", option: "0.9%", tier: "SpMlow2", initial: "응원"},
    { name: "응원 : 몬스터에게 공격 적중 시 주는 피해가", option: "1.1%", tier: "SpMmiddle", initial: "응원"},
    { name: "응원 : 몬스터에게 공격 적중 시 주는 피해가", option: "1.3%", tier: "SpMhigh", initial: "응원"},
    { name: "정기 : 무기 공격력이", option: "160", tier: "zlow1", initial: "수확"},
    { name: "정기 : 무기 공격력이", option: "190", tier: "zlow2", initial: "수확"},
    { name: "정기 : 무기 공격력이", option: "220", tier: "zmiddle", initial: "수확"},
    { name: "정기 : 무기 공격력이", option: "250", tier: "zhigh", initial: "수확"},
    { name: "] 보상 효과가", option: "8", tier: "zlow1", initial: "보상"},
    { name: "] 보상 효과가", option: "7", tier: "zlow2", initial: "보상"},
    { name: "] 보상 효과가", option: "6", tier: "zmiddle", initial: "보상"},
    { name: "] 보상 효과가", option: "5", tier: "zhigh", initial: "보상"},
    { name: "무기 공격력 +1300", option: null, tier: "Llow1", initial: "무기 공격력 +1300"},
    { name: "무기 공격력 +1600", option: null, tier: "Llow2", initial: "무기 공격력 +1600"},
    { name: "무기 공격력 +1900", option: null, tier: "Lmiddle", initial: "무기 공격력 +1900"},
    { name: "무기 공격력 +2200", option: null, tier: "Lhigh", initial: "무기 공격력 +2200"},
    { name: "] 몬스터에게 공격 적중 시 주는 피해가", option: "1.5%", tier: "low1", initial: "우월"},
    { name: "] 몬스터에게 공격 적중 시 주는 피해가", option: "2%", tier: "low2", initial: "우월"},
    { name: "] 몬스터에게 공격 적중 시 주는 피해가", option: "2.5%", tier: "middle", initial: "우월"},
    { name: "] 몬스터에게 공격 적중 시 주는 피해가", option: "3%", tier: "high", initial: "우월"},
    { name: "] 몬스터에게 공격 적중 시 치명타 피해량이", option: "4%", tier: "low1", initial: "습격"},
    { name: "] 몬스터에게 공격 적중 시 치명타 피해량이", option: "6%", tier: "low2", initial: "습격"},
    { name: "] 몬스터에게 공격 적중 시 치명타 피해량이", option: "8%", tier: "middle", initial: "습격"},
    { name: "] 몬스터에게 공격 적중 시 치명타 피해량이", option: "10%", tier: "high", initial: "습격"},
    { name: "] 몬스터에게 공격 적중 시 치명타 적중이", option: "2%", tier: "low1", initial: "정밀"},
    { name: "] 몬스터에게 공격 적중 시 치명타 적중이", option: "3%", tier: "low2", initial: "정밀"},
    { name: "] 몬스터에게 공격 적중 시 치명타 적중이", option: "4%", tier: "middle", initial: "정밀"},
    { name: "] 몬스터에게 공격 적중 시 치명타 적중이", option: "5%", tier: "high", initial: "정밀"},
    { name: "] 치명타 적중 시", option: "2%", tier: "Llow1", initial: "상처악화"},
    { name: "] 치명타 적중 시", option: "3%", tier: "Llow2", initial: "상처악화"},
    { name: "] 치명타 적중 시", option: "5%", tier: "middle", initial: "상처악화"},
    { name: "] 치명타 적중 시", option: "7%", tier: "high", initial: "상처악화"},
    { name: "] 몬스터에게 공격 적중 시 일정 확률로 10초 동안 '분개' 효과를 획득한다.", option: "23", tier: "zlow1", initial: "분개"},
    { name: "] 몬스터에게 공격 적중 시 일정 확률로 10초 동안 '분개' 효과를 획득한다.", option: "20", tier: "zlow2", initial: "분개"},
    { name: "] 몬스터에게 공격 적중 시 일정 확률로 10초 동안 '분개' 효과를 획득한다.", option: "17", tier: "zmiddle", initial: "분개"},
    { name: "] 몬스터에게 공격 적중 시 일정 확률로 10초 동안 '분개' 효과를 획득한다.", option: "14", tier: "zhigh", initial: "분개"},
    { name: "] 백어택으로 주는 피해가", option: "2.5%", tier: "low1", initial: "기습"},
    { name: "] 백어택으로 주는 피해가", option: "3%", tier: "low2", initial: "기습"},
    { name: "] 백어택으로 주는 피해가", option: "3.5%", tier: "middle", initial: "기습"},
    { name: "] 백어택으로 주는 피해가", option: "4.5%", tier: "high", initial: "기습"},
    { name: "] 헤드어택으로 주는 피해가", option: "2.5%", tier: "low1", initial: "결투"},
    { name: "] 헤드어택으로 주는 피해가", option: "3%", tier: "low2", initial: "결투"},
    { name: "] 헤드어택으로 주는 피해가", option: "3.5%", tier: "middle", initial: "결투"},
    { name: "] 헤드어택으로 주는 피해가", option: "4%", tier: "high", initial: "결투"},
    { name: "만기 도래 : 각성기 제외 일반 스킬의 치명타 피해량이", option: "20%", tier: "zlow1", initial: "적립"},
    { name: "만기 도래 : 각성기 제외 일반 스킬의 치명타 피해량이", option: "30%", tier: "zlow2", initial: "적립"},
    { name: "만기 도래 : 각성기 제외 일반 스킬의 치명타 피해량이", option: "40%", tier: "zmiddle", initial: "적립"},
    { name: "만기 도래 : 각성기 제외 일반 스킬의 치명타 피해량이", option: "50%", tier: "zhigh", initial: "적립"}

  ];

export {
        keywordList,
        grindingFilter,
        arkFilter,
        bangleJobFilter,
        engravingImg,
        dealerAccessoryFilter,
        elixirFilter,
        cardPointFilter,
        bangleFilter,
    };
